# GitHub Action for building and deploying a React app to Hostinger using FTP secrets on github

name: Build and Deploy

# This action runs on every push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository code so the job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Sets up the specific version of Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # You can change this to your preferred Node version
          cache: 'npm'

      # Step 3: Installs dependencies and builds the project
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Step 4: Deploys the built files to the FTP server
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # Your FTP server from GitHub Secrets
          server: ${{ secrets.FTP_SERVER }}
          # Your FTP username from GitHub Secrets
          username: ${{ secrets.FTP_USERNAME }}
          # Your FTP password from GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }}
          # The local directory to upload from (your build output)
          local-dir: ./dist/
          # The remote directory to upload to on the server (your website's root)
          server-dir: ./public_html/
          # Option to automatically remove files on the server that are not in the 'dist' folder
          dangerous-clean-slate: true